= 11 章導讀
Jeff Lin <jeffddt.et@gmail.com>
v1.0, June 2015

== 效能

[[效能圖片]]

== 由生活的事物說明網路

今天到公所辦理事情⋯

=== 在大廳查看該去的櫃台

也許是問大廳的志工、看地圖、或是找服務台。

可以對應到網路上的 Domain Name 查詢。

=== 走到要辦理櫃台前

也許要爬個樓梯，坐電梯。甚至有可能要走到另一棟大樓。

可以對應到與網路主機的連接，理論上會嘗試走最短的路徑。在遇到路障會試著繞路到達目的地。

=== 抽號碼牌排隊

通常能在多個櫃位得到同樣的服務，當一旦人多，就要等待叫號

等待的網路主機回應，人一多一樣要等待、服務就慢。

這也是早期人們說的「流量大就要加主機」的原因。

=== 在櫃台前說出要求

說出要求後，等待服務人員辦理相關的事務。有時會遇到服務人員向其它同事溝通，或跑到後頭的房間弄東西。

服務人員越熟練，辦理的速度越快。同樣的，主機等級越高，程式邏輯越好，就有越高的處理效率。

=== 拿到辦理的結果資料

可能只是單純的一張完成收據，或是一大包查詢的結果⋯

要傳遞的資料越多，當然就需要越多時間才能到完整的資料。

=== 閱讀拿到的結果

收據不用怎麼閱讀，好幾張法規條文讓人沒耐心，如果又夾了幾張宣傳廣告，就會讓人厭煩。

解析收到的結果，再作對應處理，是瀏覽器一直在作的工作，不過它不會抱怨，只會漠漠處理那些用不到的資料。

=== 發現還得申請其它資料時⋯

又得回到第一個步驟，重新查詢接收辦理的櫃位。

如果是同之前的櫃位能處理，可以省下查詢的時間，否則又得回到大廳再查一次。不過在網路的世界中，「走到櫃台前」與之後的動作是無法省略的。

=== 回顧之前的所有步驟

* 查詢該去的櫃台
* 走到櫃台前
* 抽號碼牌、等叫號
* 說出要求
* 取得結果
* 閱讀結果，作對應的動作

=== 能再有效率一點嗎？

以上的動作是網路世界中無法避免的，所以只能由以下兩種方式來增加效率⋯

* 減少需要傳遞的資料量
* 減少要求資料的次數

== 資訊技術的演進

雖然，現在的電腦運算能力有大幅的增加，但是網路的速度並沒有同樣快速的成長。並且⋯

* 出現了 2G, 3G 慢於一般網路速度的技術
* 需要考量設備未更新、訊息不良⋯等讓速度變慢的因素

=== 因此⋯

增加服務主機與使用者端電腦工作量，來減少在「網路上」需要的時間，是有價值的。

=== 壓縮檔案

如果把檔案先壓縮，再拿到網路上傳輸呢？

經實驗證，雖然會增加服務主機與使用者電腦的工作量，但這種作法有助於有效率的完成網頁呈現工作。

=== 發現⋯

一個純文字的檔案，包含 JavaScript 與 CSS 檔案，在經過壓縮。大體上都能節省 90% 的空間。

壓縮與解壓縮對於現在的硬體設備來說，不會花什麼時間。大部分的時間其實花在網路的資料傳輸上。

=== 所以⋯

將網頁內容壓縮傳遞已經是「標準配備」了。新一代的瀏覽器與主流伺務器都有支援。

只要互相確認能以壓縮資料傳遞，就會切換到這個模式。

所以⋯ 其實這和 UI、企劃，甚至一般程式人員都沒有關係。

== 網頁的演進

從最最原始的「純文字網頁」，到現在互動、介面優化的「網路應用程式」。

HTML 本身增加的量，並不如 JavaScript 與 CSS 檔案。

當然，也隨著增加了許多呈現需要的圖片與多媒體檔案。

=== 因此⋯

除了讓每一個檔案因為壓縮變小，減少「數量」也是被討論的議題。

省去了查詢、連結、等待⋯⋯等時間，當檔案數量很多時，改變會造成很大的差異。

=== 作法

將本來需要分多次帶回的資料，集合成一包帶回，就能夠節省往返需要的時間。

瀏覽器還不能作到將多個檔案合併成一個壓縮檔案，但是有技術能將多個檔案合併成一個。

== 對於 JS 與 CSS

對於純文字的內容，可以輕易地前後串接，讓多個檔案變成同一個。

通常會利用工具，開發時仍然是多個檔案，在佈署前再將檔案合併。

JS 與 CSS 在開發需要分散，才容易分開測試。因此分散檔案仍然有其必要性。

=== 還沒結束

為了方便編輯、閱讀，JavaScript 與 CSS 會利用換行、縮排等排版技術。

那些空白、縮排、換行字元省下來，有的甚至能夠省下 1/4 的檔案大小。

同樣的，拿掉排版後會很難閱讀取修改，因此的通常是在發佈前，利用工具製作這些檔案。

=== 再走火入魔一些⋯

程式中利用變數來記錄資料，那麼將變數的名稱改短，整個檔案的字母數量也會跟著減少。

和上述的作法整合，被稱作程式檔案的「最佳化」，枋間不只一種工具能夠作到。


== 關於圖片

對於應用於整個網站的圖示，可以將之合併在一個檔案中。

利用 CSS 設定背景圖片位置的方式，調整組合圖的「露出」部分。

=== 圖示文字

圖片合併是很常見的作法，不過對於一些較舊的瀏覽器，不支援背景圖的縮放。因此要作大不尺寸大小的圖示。

近來漸漸開始使用「圖示文字」取代，尺寸更小、也沒有縮放的問題。

=== 同場加映

隨著 Flash 漸漸不被支援，越來越多 HTML 5 動畫被製作。不過 HTML 沒有既有的動畫格式。
因此實現的方式，就是傳入一組圖片，像卡通一樣的切換達到動畫的效果。

因此，相關未來將圖片組成一大張大圖，會是一個被大量使用的技巧。

=== 色彩優化

利用演算法，將圖片中顏色相近的點，設成同一種顏色。
可以在不明顯影響結果的狀態下，讓檔案能夠變得更小。

== 只載入"必要"的內容

使用框架(framework)可以加速開發速度，某些層面的提高程式品質。但畢竟別人的框架不是單為自己的專案所設計。
因此會帶有一些專案用不到的功能，這是無可避免。

如果⋯能夠只讀需要的部分該有多好⋯

=== 將每一個框架拆細，只讀需要的

以 jQuery ui 套件，也許可以拆成⋯
* 

=== 利用公用的打包套件下載

=== 使用自己的打包工具

=== 當需要某個功能時才載入

=== 實際應用呢？

需要對於整體程式有相當程度的理解，並具有一定的技術能力。才能進行此工作。

然而，對於會變動的網站而言，每一次的修改都可能對既有的截入策略產生衝擊。

== 放到更快的網路上

有人把網路比喻成水管，水管越粗，水流越快。對於快速的網路環境，被稱為「大水管」。

將網頁內容放在「大水管」，能夠最大限度的提高網頁的傳輸效率。

=== 花錢買頻寬

=== 選擇有多負截平衡的主機

=== 資料與檔案分離

=== 現實是⋯

當用戶所在的網路環境很不理想，網路再快也得遷就整個路徑中最低的那個速度。

因此，在台灣的環境，通常要到一定數量流量，需要應付同時許多人的要求，這時候才比較能看出大流量的差別。

== 理想與現實

由於人力、技術掌握的問題。在台灣比較少看到這種處理模式。可能的原因是⋯

* 沒有發佈的概念，程式寫完就直接往主機上丟。
* 技術掌握不夠，程式新手無法理解這樣的過程
* 改動過於頻繁，加上沒有自動處理的機制，導致最佳化成為一種負擔

== 結論

想要得到上述所有的優化好處，在不斷變動、擴充的開發現況下。
需要一個完善的自動化發佈流程，以節省大量的重覆工作，節省優化工作所佔用的開發時間。

如果純手工的方式來處理，在開發時程有限的前提下，也就只能盡盡人事了。
